// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";
import { User } from "./user_type";
// Mark import as potentially unused
declare type __keep_User = User;
import { ServerEvents } from "./server_events_type";
// Mark import as potentially unused
declare type __keep_ServerEvents = ServerEvents;
import { ServerStatus } from "./server_status_type";
// Mark import as potentially unused
declare type __keep_ServerStatus = ServerStatus;


export type Server = {
  serverId: string,
  owner: User,
  events: ServerEvents,
  status: ServerStatus,
};
/**
 * An object for generated helper functions.
 */
export const Server = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    return __AlgebraicTypeValue.Product({
      elements: [
        { name: "serverId", algebraicType: __AlgebraicTypeValue.String},
        { name: "owner", algebraicType: User.getTypeScriptAlgebraicType()},
        { name: "events", algebraicType: ServerEvents.getTypeScriptAlgebraicType()},
        { name: "status", algebraicType: ServerStatus.getTypeScriptAlgebraicType()},
      ]
    });
  },

  serialize(writer: __BinaryWriter, value: Server): void {
    __AlgebraicTypeValue.serializeValue(writer, Server.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): Server {
    return __AlgebraicTypeValue.deserializeValue(reader, Server.getTypeScriptAlgebraicType());
  },

}

export default Server;


